---
abstract: 'defines RGB values for common color names'
author:
  - 'Robert Rothenberg <rrwo@cpan.org>'
build_requires:
  File::Spec: '0'
  FileHandle: '0'
  IO::File: '0'
  Module::Metadata: '0'
  Test::Exception: '0'
  Test::More: '0'
  Test::Most: '0'
  constant: '0'
  lib: '0'
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
keywords:
  - color
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Graphics-ColorNames
provides:
  Graphics::ColorNames:
    file: lib/Graphics/ColorNames.pm
    version: v3.5.0
  Graphics::ColorNames::X:
    file: lib/Graphics/ColorNames/X.pm
    version: v3.5.0
requires:
  Exporter: '5.57'
  Module::Load: '0.10'
  Module::Loaded: '0'
  perl: v5.10.0
  version: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Graphics-ColorNames
  repository: git://github.com/robrwo/Graphics-ColorNames.git
version: v3.5.0
x_authority: cpan:RRWO
x_contributors:
  - 'Alan D. Salewski <alans@cji.com>'
  - 'Steve Pomeroy <xavier@cpan.org>'
  - '"chemboy" <chemboy@perlmonk.org>'
  - 'Magnus Cedergren <magnus@mbox604.swipnet.se>'
  - 'Gary Vollink <gary@vollink.com>'
  - 'Claus Färber <cfaerber@cpan.org>'
  - 'Andreas J. König <andk@cpan.org>'
  - 'Slaven Rezić <slaven@rezic.de>'
x_generated_by_perl: v5.28.1
x_serialization_backend: 'YAML::Tiny version 1.73'
