--- #YAML:1.0
name: Graphics-ColorNames
version: 1.06
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: defines RGB values for common color names
license: perl
requires:
  Carp: 0
  IO::File: 0
  Module::Load: 0.1
  base: 0
  perl: 5.6.0
recommends:
  Pod::Coverage: 0
  Test::Pod: 1
  Test::Prereq: 0
build_requires:
  Test::More: 0
provides:
  Graphics::ColorNames:
    file: lib/Graphics/ColorNames.pm
    version: 1.06
  Graphics::ColorNames::HTML:
    file: lib/Graphics/ColorNames/HTML.pm
    version: 1.11
  Graphics::ColorNames::Netscape:
    file: lib/Graphics/ColorNames/Netscape.pm
    version: 1.05
  Graphics::ColorNames::Windows:
    file: lib/Graphics/ColorNames/Windows.pm
    version: 1.03
  Graphics::ColorNames::X:
    file: lib/Graphics/ColorNames/X.pm
    version: 1.06
  Graphics::ColourNames:
    file: lib/Graphics/ColourNames.pm
    version: 1.06
generated_by: Module::Build version 0.2607
